// <auto-generated />
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250408112412_SeedCouponTables")]
    partial class SeedCouponTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "SAVE10",
                            DiscountAmount = 10.0,
                            MinAmount = 50
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "WELCOME20",
                            DiscountAmount = 20.0,
                            MinAmount = 100
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "FLASH30",
                            DiscountAmount = 30.0,
                            MinAmount = 150
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "SUMMER15",
                            DiscountAmount = 15.0,
                            MinAmount = 75
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "WINTER25",
                            DiscountAmount = 25.0,
                            MinAmount = 120
                        },
                        new
                        {
                            CouponId = 6,
                            CouponCode = "LOYAL50",
                            DiscountAmount = 50.0,
                            MinAmount = 200
                        },
                        new
                        {
                            CouponId = 7,
                            CouponCode = "NEWUSER5",
                            DiscountAmount = 5.0,
                            MinAmount = 25
                        },
                        new
                        {
                            CouponId = 8,
                            CouponCode = "HOLIDAY40",
                            DiscountAmount = 40.0,
                            MinAmount = 180
                        },
                        new
                        {
                            CouponId = 9,
                            CouponCode = "SPECIAL15",
                            DiscountAmount = 15.0,
                            MinAmount = 60
                        },
                        new
                        {
                            CouponId = 10,
                            CouponCode = "RETURN10",
                            DiscountAmount = 10.0,
                            MinAmount = 40
                        },
                        new
                        {
                            CouponId = 11,
                            CouponCode = "AUTUMN20",
                            DiscountAmount = 20.0,
                            MinAmount = 90
                        },
                        new
                        {
                            CouponId = 12,
                            CouponCode = "SPRING25",
                            DiscountAmount = 25.0,
                            MinAmount = 125
                        },
                        new
                        {
                            CouponId = 13,
                            CouponCode = "WEEKEND15",
                            DiscountAmount = 15.0,
                            MinAmount = 65
                        },
                        new
                        {
                            CouponId = 14,
                            CouponCode = "SALE30",
                            DiscountAmount = 30.0,
                            MinAmount = 140
                        },
                        new
                        {
                            CouponId = 15,
                            CouponCode = "VIP20",
                            DiscountAmount = 20.0,
                            MinAmount = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
